# Copyright (c) 2024 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl

title: "OKE: AI/ML Quickstart (Kubernetes)"
description: Cluster software for running AI/ML workloads on Container Engine for Kubernetes
# stackDescription: "TODO Add stack description"
# informationalText: "TODO Add informational text"
logoUrl: "https://repository-images.githubusercontent.com/177214476/c5cb7a2b-f502-4632-a1f5-df721534af5a"
schemaVersion: 1.1.0
version: "20230304"
locale: "en"

variableGroups:
  - title: "Hidden"
    visible: false
    variables:
      - api_fingerprint
      - current_user_ocid
      - region
      - tenancy_ocid
      - api_fingerprint
      - oci_auth
      - oci_profile
      - monitoring_namespace
      - prom_server_memory_limit
      - scrape_interval_seconds
      - scrape_timeout_seconds
      - prom_server_memory_request

  - title: Cluster
    variables:
      - compartment_ocid
      - cluster_id

  - title: DCGM Exporter
    variables:
      - install_dcgm_exporter
      - dcgm_exporter_chart_version

  - title: Metrics server
    variables:
      - install_metrics_server
      - metrics_server_chart_version

  - title: Prometheus
    variables:
      - install_prometheus_stack
      - prometheus_stack_chart_version
      - retention_storageclass
      - retention_hours
      - retention_gb
      - install_prometheus_adapter
      - prometheus_adapter_chart_version
      - install_prometheus_pushgateway
      - prometheus_pushgateway_chart_version
      - install_grafana
      - install_grafana_dashboards

variables:
  current_user_ocid:
    title: User
    type: ocid
  oci_auth:
    default: null
  oci_profile:
    default: null
  tenancy_ocid:
    title: Tenancy
    type: oci:identity:compartment:id
    required: true
  region:
    required: true
    title: Region
    type: oci:identity:region:name

  # Cluster
  compartment_ocid:
    title: Compartment
    description: The default compartment for created resources
    type: oci:identity:compartment:id
    required: true
  cluster_id:
    type: oci:container:cluster:id
    title: Cluster
    description: The Container Engine for Kubernetes cluster
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}

  # Installation
  install_dcgm_exporter:
    title: DCGM Exporter
    description: Install NVIDIA DCGM Exporter
    type: boolean
    required: true
  dcgm_exporter_chart_version:
    title: DCGM Exporter chart version
    type: string
    required: true
    visible: ${install_dcgm-exporter}

  install_prometheus_stack:
    title: Prometheus stack
    description: Install Prometheus server, Grafana, and Node Exporter
    type: boolean
    required: true
  prometheus_stack_chart_version:
    title: Prometheus stack chart version
    type: string
    required: true
    visible: ${install_prometheus_stack}
  prom_server_memory_request:
    title: Prometheus server memory request
    description: "Memory reserved for Prometheus server. You can express memory as percentage of node allocatable with '%' suffix, or a plain integer/fixed-point integer with one of these suffixes: E, P, T, G, M, K, Ei, Pi, Ti, Gi, Mi, Ki."
    required: false
    visible: ${install_prometheus_stack}
  prom_server_memory_limit:
    title: Prometheus server memory limit
    description: "Maximum amount of memory usable for Prometheus server. You can express memory as percentage of node allocatable with '%' suffix, or a plain integer/fixed-point integer with one of these suffixes: E, P, T, G, M, K, Ei, Pi, Ti, Gi, Mi, Ki."
    required: false
    #visible: ${install_prometheus_stack}
  retention_storageclass:
    title: Storage class
    description: Kubernetes storage class for Prometheus server data
    type: string
    required: true
    visible: ${install_prometheus_stack}
  retention_hours:
    title: Retention (Hours)
    description: When to remove old data from TSDB
    type: number
    required: true
    visible: ${install_prometheus_stack}
  retention_gb:
    title: Retention (GB)
    description: The maximum number of gigabytes of storage blocks to retain in TSDB. The oldest data will be removed first. A value of 0 disables retention by size. Only the persistent blocks are deleted to honor this retention although WAL and m-mapped chunks are counted in the total size, so the minimum requirement for the disk is the peak space taken by the wal (the WAL and Checkpoint) and chunks_head (m-mapped Head chunks) directory combined (peaks every 2 hours).
    type: number
    required: true
    visible: ${install_prometheus_stack}

  install_grafana:
    title: Grafana
    description: Install Grafana
    type: boolean
    required: true
    visible: ${install_prometheus_stack}
  install_grafana_dashboards:
    title: Grafana dashboards
    description: Install Grafana dashboards
    type: boolean
    required: true
    visible:
      and:
      - ${install_prometheus_stack}
      - ${install_grafana}

  install_prometheus_pushgateway:
    title: Prometheus push gateway
    description: Install Prometheus push gateway
    type: boolean
    required: true
  prometheus_pushgateway_chart_version:
    title: Prometheus push gateway Helm chart version
    type: string
    visible: ${install_prometheus_pushgateway}
    required: true

  install_prometheus_adapter:
    title: Prometheus adapter
    description: Install Prometheus adapter
    type: boolean
    required: true
  prometheus_adapter_chart_version:
    title: Prometheus adapter Helm chart version
    type: string
    visible: ${install_prometheus_adapter}
    required: true

  install_metrics_server:
    title: Metrics Server
    description: Install Kubernetes Metrics Server
    type: boolean
    required: true
  metrics_server_chart_version:
    title: Helm chart version
    type: string
    visible: ${install_metrics_server}
    required: true


outputGroups:
  - title: Cluster
    outputs:
      - cluster_id

  - title: Kubernetes metrics server
    outputs:
      - metrics_server_version

  - title: Prometheus
    outputs:
      - prom_port_forward
      - retention_hours
      - retention_gb
      - retention_storageclass
      - prometheus_stack_version
      - prometheus_adapter_version

outputs:
  # Cluster
  cluster_id:
    title: Cluster
    type: ocid
  cluster_endpoint:
    title: Endpoint
    type: copyableString
  kubeconfig:
    title: Kubeconfig
    type: copyableString
  service_account_secret_name:
    title: Service account secret
    type: copyableString

  retention_hours:
    title: Retention (Hours)
    description: When to remove old data from TSDB
    type: number
  retention_gb:
    title: Retention (GB)
    description: The maximum number of gigabytes of storage blocks to retain in TSDB. The oldest data will be removed first. A value of 0 disables retention by size. Only the persistent blocks are deleted to honor this retention although WAL and m-mapped chunks are counted in the total size, so the minimum requirement for the disk is the peak space taken by the wal (the WAL and Checkpoint) and chunks_head (m-mapped Head chunks) directory combined (peaks every 2 hours).
    type: number

  # Extras
  prometheus_version:
    title: Prometheus
    type: string
  prometheus_adapter_version:
    title: Prometheus adapter
    type: string
  metrics_server_version:
    title: Metrics server
    type: string
  scrape_interval_seconds:
    title: Scrape Interval seconds
    type: string